name: C/C++ CI

on:
  push:
    branches: [ "main", "testing", "development" ]
  pull_request:
    branches: [ "main", "testing" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: make engine
    - run: make engine
      name: make cli
    - run: make cli
      name: clisuite
    - run: /home/runner/work/ioe/ioe/engine.exe 0
      name: make test
    - run: make test
      name: testsuite
    - run: /home/runner/work/ioe/ioe/tester.exe 0
      name: make help
    - run: make help
      name: helpsuite
    - run: /home/runner/work/ioe/ioe/helper.exe 0
