name: IoE Workflow 

on:
  push:
    branches: [ "main", "testing", "development" ]
  pull_request:
    branches: [ "main", "testing" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build engine 
      run: make engine
    - name: build audiosuite
      run: make audio
    - name: test audiosuite
      run: /home/runner/work/ioe/ioe/audio.exe
    - name: build cli 
      run: make cli
    - name: test clisuite 
      run: /home/runner/work/ioe/ioe/engine.exe 0
    - name: build testsuite
      run: make test
    - name: test testsuite
      run: /home/runner/work/ioe/ioe/tester.exe 0
    - name: build helpsuite
      run: make help
    - name: test helpsuite
      run: /home/runner/work/ioe/ioe/helper.exe 0
