name: IoE Workflow 

on:
  push:
    branches: [ "main", "testing", "development" ]
  pull_request:
    branches: [ "main", "testing" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build core
      run: make -j8 core
    - name: build audiosuite
      run: make -j8 audiosuite
    - name: build clisuite
      run: make -j8 clisuite
    - name: build helpsuite
      run: make -j8 helpsuite
    - name: build testsuite
      run: make -j8 testsuite
    - name: test audiosuite
      run: /home/runner/work/ioe/ioe/bin/audiosuite.exe
    - name: test clisuite 
      run: /home/runner/work/ioe/ioe/bin/clisuite.exe
    - name: test testsuite
      run: /home/runner/work/ioe/ioe/bin/testsuite.exe 0
    - name: test helpsuite
      run: /home/runner/work/ioe/ioe/bin/helpsuite.exe
