name: IoE Workflow 

on:
  push:
    branches: [ "main", "testing", "development" ]
  pull_request:
    branches: [ "main", "testing" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build engine 
      run: make -j8 engine
    - name: build audiosuite
      run: make -j8 audio
    - name: build cli 
      run: make -j8 cli
    - name: build helpsuite
      run: make -j8 help
    - name: build testsuite
      run: make -j8 test
    - name: test audiosuite
      run: /home/runner/work/ioe/ioe/bin/mixer.exe
    - name: test clisuite 
      run: /home/runner/work/ioe/ioe/bin/engine.exe
    - name: test testsuite
      run: /home/runner/work/ioe/ioe/bin/tester.exe 0
    - name: test helpsuite
      run: /home/runner/work/ioe/ioe/bin/helper.exe
