Name: C/C++ CI

on:
  push:
    branches: [ "main", "testing", "development" ]
  pull_request:
    branches: [ "main", "testing" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Make Engine
    - run: make engine
      name: build engine 
    - run: make audio
      name: build audiosuite
    - run: /home/runn/work/ioe/ioe/audio.exe
      name: test audiosuite
    - run: make cli
      name: build cli 
    - run: /home/runner/work/ioe/ioe/engine.exe 0
      name: test clisuite 
    - run: make test
      name: build testsuite
    - run: /home/runner/work/ioe/ioe/tester.exe 0
      name: test testsuite
    - run: make help
      name: build helpsuite
    - run: /home/runner/work/ioe/ioe/helper.exe 0
      name: test helpsuite
