name: C/C++ CI

on:
  push:
    branches: [ "main", "testing", "development" ]
  pull_request:
    branches: [ "main", "testing" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make cli
      run: make cli
    - name: clisuite
      run: ./engine.js 0
    - name: make test
      run: make test
    - name: testsuite
      run: ./tester.js 0
    - name: make help
      run: make help
    - name: helpsuite
      run: ./helper.js 0
