name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: testing
      run: make core/ops
    - name: make
      run: make
    - name: make test
      run: make test
    - name: make help
      run: make help
    - name: testsuite
      run: ./tester 0
    - name: helpsuite
      run: ./helper 0
